In [10]:
import os
os.path.join??

In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])

In [13]:
a

array([1, 2, 3])

In [15]:
a = np.array([[1,2,3],[4,5,6]])

In [16]:
a[0]

array([1, 2, 3])

In [17]:
a.shape

(2, 3)

In [18]:
a.ndim

2

In [19]:
a.dtype.name

'int64'

In [20]:
a.size

6

In [21]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [23]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [24]:
np.zeros((3, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [25]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.nan

nan

In [27]:
[np.nan] * 10

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [29]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
a = np.arange(24).reshape(2, 3, 4)

In [36]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
np.arange(1000).reshape(10, 100)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 17

In [38]:
x = np.arange(0, 10, 2)
y = np.arange(5)
z = np.arange(0, 100, 20)

In [39]:
np.append(x, y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [40]:
np.vstack([x, y, z])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [41]:
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

In [43]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(5)
a - b

array([10, 19, 28, 37, 46])

In [44]:
a * b

array([  0,  20,  60, 120, 200])

In [45]:
a < 30

array([ True,  True, False, False, False])

In [46]:
b *= 3

In [47]:
b

array([ 0,  3,  6,  9, 12])

In [48]:
a = np.random.random((2, 3))
a

array([[0.7451891 , 0.54197755, 0.49075932],
       [0.16917172, 0.12166777, 0.17738621]])

In [49]:
a.sum()

2.2461516667759915

In [50]:
a.min()

0.12166776970238702

In [51]:
a.mean()

0.37435861112933194

In [52]:
a = np.arange(12).reshape(3, 4)

In [53]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [56]:
a.sum(axis=1)

array([ 6, 22, 38])

In [57]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])